### ISSUE TITLE
Please update the plugin for IntelliJ version 2022.3

### ISSUE THREAD

**Issue by ssj4xxx** [fffguo/console-beautiful-json#1]
Please update it to be compatible with the new version of IDE (IntelliJ IDEA 2022.3, DataGrip 2022.3).
Thank you so much!

**Comment by fffguo** [comment]
ok

**Comment by fffguo** [comment]
Manual installation：https://github.com/fffguo/console-beautiful-json/releases/tag/1.0.2-RELEASE
or
Waiting for the store audit
